export const img = (seed, w = 800, h = 600) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const contact = {
  phone: '+91 00000 00000',
  phoneHref: 'tel:+910000000000',
  whatsappHref: 'https://wa.me/910000000000',
  instagramHandle: '@profitmeals',
  instagramHref: 'https://instagram.com',
  email: 'hello@profitmeals.in',
  emailHref: 'mailto:hello@profitmeals.in',
  serviceArea: 'City & suburbs',
};

export const meals = [
  {
    slug: 'chicken-tikka-protein-bowl',
    name: 'Chicken Tikka Protein Bowl',
    desc: 'Grilled chicken, brown rice, fresh vegetables and signature sauce.',
    rating: '4.8',
    reviews: 132,
    kcal: 520, protein: 42, carbs: 48, fat: 16,
    tags: ['High Protein', 'Best Seller'],
    diet: 'Non-Vegetarian',
    goals: ['Muscle Gain', 'High Protein'],
    price: '₹329',
    portion: '420g box · serves one',
    allergens: ['Dairy', 'Mustard'],
    ingredients: [
      { name: 'Chicken breast', qty: '180g' },
      { name: 'Brown rice', qty: '120g' },
      { name: 'Bell peppers', qty: '60g' },
      { name: 'Hung curd', qty: '40g' },
      { name: 'Tikka spice mix', qty: '8g' },
      { name: 'Olive oil', qty: '5g' },
    ],
  },
  {
    slug: 'paneer-makhani-power-bowl',
    name: 'Paneer Makhani Power Bowl',
    desc: 'Marinated paneer, millet rice and a lighter makhani gravy.',
    rating: '4.7', reviews: 98,
    kcal: 610, protein: 34, carbs: 52, fat: 26,
    tags: ['Vegetarian', 'High Protein'],
    diet: 'Vegetarian',
    goals: ['Vegetarian', 'High Protein'],
    price: '₹299',
    portion: '430g box · serves one',
    allergens: ['Dairy'],
    ingredients: [
      { name: 'Paneer', qty: '150g' },
      { name: 'Millet rice', qty: '110g' },
      { name: 'Tomato gravy', qty: '90g' },
      { name: 'Cashew paste', qty: '15g' },
    ],
  },
  {
    slug: 'grilled-fish-quinoa',
    name: 'Grilled Fish & Quinoa',
    desc: 'Lemon-pepper basa, quinoa pilaf and steamed greens.',
    rating: '4.9', reviews: 76,
    kcal: 480, protein: 44, carbs: 38, fat: 14,
    tags: ['Low Calorie', 'Muscle Gain'],
    diet: 'Non-Vegetarian',
    goals: ['Muscle Gain', 'Weight Loss'],
    price: '₹379',
    portion: '400g box · serves one',
    allergens: ['Fish'],
    ingredients: [
      { name: 'Basa fillet', qty: '170g' },
      { name: 'Quinoa', qty: '100g' },
      { name: 'Broccoli & beans', qty: '80g' },
    ],
  },
  {
    slug: 'egg-white-masala-wrap',
    name: 'Egg White Masala Wrap',
    desc: 'Egg white bhurji in a whole-wheat wrap with mint chutney.',
    rating: '4.6', reviews: 54,
    kcal: 340, protein: 28, carbs: 32, fat: 10,
    tags: ['Breakfast', 'Low Calorie'],
    diet: 'Eggetarian',
    goals: ['Breakfast', 'Weight Loss'],
    price: '₹199',
    portion: '260g · serves one',
    allergens: ['Egg', 'Gluten'],
    ingredients: [
      { name: 'Egg whites', qty: '160g' },
      { name: 'Whole-wheat wrap', qty: '1 pc' },
      { name: 'Mint chutney', qty: '20g' },
    ],
  },
  {
    slug: 'lean-keema-brown-rice',
    name: 'Lean Keema Brown Rice',
    desc: 'Slow-cooked lean mutton keema with brown rice and salad.',
    rating: '4.8', reviews: 121,
    kcal: 560, protein: 46, carbs: 44, fat: 20,
    tags: ['Muscle Gain', 'Best Seller'],
    diet: 'Non-Vegetarian',
    goals: ['Muscle Gain', 'High Protein'],
    price: '₹349',
    portion: '430g box · serves one',
    allergens: [],
    ingredients: [
      { name: 'Lean mutton keema', qty: '170g' },
      { name: 'Brown rice', qty: '120g' },
      { name: 'Kachumber salad', qty: '70g' },
    ],
  },
  {
    slug: 'rajma-chawal-fit-bowl',
    name: 'Rajma Chawal Fit Bowl',
    desc: 'Rajma cooked low-oil, brown rice, kachumber and curd.',
    rating: '4.5', reviews: 63,
    kcal: 520, protein: 26, carbs: 72, fat: 12,
    tags: ['Vegetarian', 'Balanced'],
    diet: 'Vegetarian',
    goals: ['Vegetarian', 'Eat Healthy'],
    price: '₹249',
    portion: '450g box · serves one',
    allergens: ['Dairy'],
    ingredients: [
      { name: 'Rajma', qty: '150g' },
      { name: 'Brown rice', qty: '120g' },
      { name: 'Curd', qty: '60g' },
    ],
  },
  {
    slug: 'peri-peri-chicken-salad',
    name: 'Peri Peri Chicken Salad',
    desc: 'Peri peri chicken, greens, chickpeas and a yoghurt dressing.',
    rating: '4.7', reviews: 88,
    kcal: 380, protein: 38, carbs: 18, fat: 16,
    tags: ['Weight Loss', 'Low Calorie'],
    diet: 'Non-Vegetarian',
    goals: ['Weight Loss', 'Eat Healthy'],
    price: '₹319',
    portion: '350g box · serves one',
    allergens: ['Dairy'],
    ingredients: [
      { name: 'Chicken breast', qty: '150g' },
      { name: 'Mixed greens', qty: '90g' },
      { name: 'Chickpeas', qty: '60g' },
    ],
  },
  {
    slug: 'soya-chaap-protein-box',
    name: 'Soya Chaap Protein Box',
    desc: 'Tandoori soya chaap, jeera rice and roasted vegetables.',
    rating: '4.4', reviews: 41,
    kcal: 540, protein: 38, carbs: 46, fat: 20,
    tags: ['Vegetarian', 'High Protein'],
    diet: 'Vegetarian',
    goals: ['Vegetarian', 'High Protein'],
    price: '₹279',
    portion: '420g box · serves one',
    allergens: ['Soy', 'Gluten'],
    ingredients: [
      { name: 'Soya chaap', qty: '160g' },
      { name: 'Jeera rice', qty: '110g' },
      { name: 'Roasted vegetables', qty: '80g' },
    ],
  },
  {
    slug: 'overnight-oats-whey',
    name: 'Overnight Oats & Whey',
    desc: 'Rolled oats, whey, chia and seasonal fruit.',
    rating: '4.6', reviews: 70,
    kcal: 320, protein: 24, carbs: 40, fat: 8,
    tags: ['Breakfast', 'Snacks'],
    diet: 'Vegetarian',
    goals: ['Breakfast', 'Eat Healthy'],
    price: '₹179',
    portion: '300g jar · serves one',
    allergens: ['Dairy', 'Nuts'],
    ingredients: [
      { name: 'Rolled oats', qty: '60g' },
      { name: 'Whey protein', qty: '25g' },
      { name: 'Chia seeds', qty: '10g' },
    ],
  },
];

export const categories = [
  'All', 'High Protein', 'Weight Loss', 'Muscle Gain',
  'Vegetarian', 'Non-Vegetarian', 'Breakfast', 'Snacks',
];

export const goals = [
  { title: 'Build Muscle', blurb: 'High-protein meals designed to support muscle growth.', filter: 'Muscle Gain', seed: 'goal-muscle' },
  { title: 'Lose Weight', blurb: 'Balanced, calorie-conscious meals.', filter: 'Weight Loss', seed: 'goal-weight' },
  { title: 'Eat Healthy', blurb: 'Nutritious meals for everyday wellness.', filter: 'Vegetarian', seed: 'goal-healthy' },
  { title: 'Stay Active', blurb: 'Balanced meals for an active lifestyle.', filter: 'High Protein', seed: 'goal-active' },
];

export const plans = [
  {
    slug: 'starter', name: 'Starter Plan', popular: false,
    blurb: 'For people getting started with healthy eating.',
    meals: 12, weeks: 2, protein: '25–35g', kcal: '350–500',
    who: 'Anyone replacing two or three meals a week with something better.',
    benefits: ['Balanced macros on every box', 'Swap any meal up to 24h before', 'Fixed delivery slot'],
  },
  {
    slug: 'fitness', name: 'Fitness Plan', popular: true,
    blurb: 'Higher protein meals designed for active lifestyles.',
    meals: 24, weeks: 4, protein: '35–45g', kcal: '450–650',
    who: 'People training four or more days a week who need protein to land daily.',
    benefits: ['Higher protein across the week', 'Pre and post workout timing', 'Monthly macro report'],
  },
  {
    slug: 'transformation', name: 'Transformation Plan', popular: false,
    blurb: 'Structured meals for people working toward specific fitness goals.',
    meals: 48, weeks: 8, protein: '40–55g', kcal: '400–700',
    who: 'Anyone on a cut or a bulk with a target date in mind.',
    benefits: ['Goal-based meal rotation', 'Nutritionist check-in', 'Weekly macro review'],
  },
];

export const testimonials = [
  { quote: 'Getting enough protein every day used to be difficult. These meals made it incredibly easy.', name: 'Customer Name', tag: 'Muscle Gain', seed: 'person-1' },
  { quote: 'I stopped guessing my calories. The macros are on the box, so I just eat and train.', name: 'Customer Name', tag: 'Weight Loss', seed: 'person-2' },
  { quote: 'Healthy food that actually tastes like food. My whole week of lunches is sorted.', name: 'Customer Name', tag: 'Healthy Lifestyle', seed: 'person-3' },
];

export const faqs = [
  { q: 'Are the meals high in protein?', a: 'Most meals carry 30g or more, and several go past 45g. The exact figure is printed on every box and listed on every meal page.' },
  { q: 'Do you offer vegetarian meals?', a: 'Yes. Roughly half the rotation is vegetarian, and there are eggetarian options too. Filter the menu by diet to see them.' },
  { q: 'How are calories calculated?', a: 'Every ingredient is weighed on a scale before cooking, so the label reflects what is actually in the box rather than a recipe estimate.' },
  { q: 'Do you offer meal plans?', a: 'Three of them — Starter, Fitness and Transformation. We confirm the rotation over a call before your first delivery.' },
  { q: 'Are meals freshly prepared?', a: 'Cooked the morning they are delivered. Nothing is frozen and nothing is held over from a previous day.' },
  { q: 'Do you provide customized meals?', a: 'On plans, yes. Tell us your allergies, dislikes and macro targets and we build the rotation around them.' },
  { q: 'Where do you deliver?', a: 'Three zones across the city, each with fixed slots. Central gets three slots a day, the outer ring gets one.' },
  { q: 'How can I order?', a: 'Over WhatsApp or by phone. There is no checkout on this site — we confirm everything with you directly.' },
];

export const zones = [
  { zone: 'Central zone', slots: '7am, 1pm, 8pm' },
  { zone: 'North & west suburbs', slots: '7am, 1pm' },
  { zone: 'Outer ring', slots: '1pm only' },
];
